- hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  gather_facts: no
  pre_tasks:
    - raw: dnf install -y python python2-dnf
  tasks:
    - name: "gather facts"
      setup:
    - dnf:
        name: libselinux-python
        state: latest
    - user:
        name: mluk
        group: wheel
    - authorized_key:
        user: mluk
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - dnf:
        name: docker
        state: latest